catalog:
  '@changesets/cli': '^3.0.1'
  '@commitlint/cli': '^21.2.2'
  '@commitlint/config-conventional': '^21.2.2'
  '@eslint/js': '^10.0.1'
  '@types/node': '26.4.0'
  '@typescript-eslint/eslint-plugin': '^8.68.0'
  '@typescript-eslint/parser': '^8.68.0'
  'cssnano': '^9.0.1'
  'eslint': '^10.9.1'
  'eslint-config-prettier': '^10.1.8'
  'eslint-plugin-prettier': '^5.5.6'
  'husky': '^9.1.7'
  'lint-staged': '^17.4.1'
  'postcss': '^8.5.26'
  'prettier': '^3.9.6'
  'style-dictionary': '^5.5.2'
  'tsx': '^4.23.12'
  'typescript': '7.0.2'
  'vite': '^8.2.2'
  'vite-plugin-dts': '^5.0.3'
